[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknow-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknow-linux-musl",

    "x86_64-apple-darwin",
    "aarch64-apple-darwin",

    "x86_64-pc-windows-msvc",
]
all-features = true

[advisories]
ignore = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["OpenSSL"], crate = "aws-lc-sys" },
    { allow = ["OpenSSL"], crate = "ring" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]


[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"

skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
